# k8s/jobs/historical-data-cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: historical-compute-services
spec:
  schedule: "0 0 */21 * *" # Medianoche cada 21 d√≠as
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: compute-services
              image: trader-charts-compute-services
              imagePullPolicy: Never
              command: ["python", "-m", "mains.main_collect_historical_data"]
              envFrom:
                - configMapRef:
                    name: compute-services-config
          restartPolicy: Never
