# k8s/jobs/train-sentiment-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: train-sentiment-model
spec:
  template:
    spec:
      containers:
        - name: compute-services
          image: trader-charts-compute-services
          imagePullPolicy: Never
          command: ["python", "-m", "mains.main_finetune_sentiment_model"]
          envFrom:
            - configMapRef:
                name: compute-services-config
      restartPolicy: Never
  backoffLimit: 0
